-- 保險業風險管理趨勢論壇核心資料模型。
-- 正式部署由 Sites 套用；執行環境亦以 CREATE TABLE IF NOT EXISTS 安全初始化。
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, year INTEGER NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, is_current INTEGER NOT NULL DEFAULT 0, is_published INTEGER NOT NULL DEFAULT 0, name_zh TEXT NOT NULL, name_en TEXT NOT NULL, theme_zh TEXT NOT NULL, theme_en TEXT NOT NULL, concept_zh TEXT NOT NULL, concept_en TEXT NOT NULL, date_label TEXT NOT NULL, time_label TEXT NOT NULL, checkin_label TEXT NOT NULL, location_name TEXT NOT NULL, location_address TEXT NOT NULL, venue_detail TEXT NOT NULL, organizer TEXT NOT NULL, hero_url TEXT NOT NULL DEFAULT '', audience TEXT NOT NULL, fee_label TEXT NOT NULL, capacity_label TEXT NOT NULL, deadline_label TEXT NOT NULL, requires_approval INTEGER NOT NULL DEFAULT 1, registration_open INTEGER NOT NULL DEFAULT 1, waitlist_enabled INTEGER NOT NULL DEFAULT 1, transport_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS focuses (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), title TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, is_visible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS speakers (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), name_zh TEXT NOT NULL, name_en TEXT NOT NULL DEFAULT '', organization TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', speaker_type TEXT NOT NULL DEFAULT '', topic TEXT NOT NULL DEFAULT '', bio TEXT NOT NULL DEFAULT '', photo_url TEXT NOT NULL DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, is_visible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS agenda_items (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), day_label TEXT NOT NULL, period TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, participants TEXT NOT NULL, venue TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, is_visible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS faqs (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), question TEXT NOT NULL, answer TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, is_visible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS dialogues (id TEXT PRIMARY KEY, year INTEGER NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, theme TEXT NOT NULL, date_label TEXT NOT NULL, location TEXT NOT NULL, background TEXT NOT NULL, insights TEXT NOT NULL, participants_count TEXT NOT NULL, speakers_count TEXT NOT NULL, sessions_count TEXT NOT NULL, is_published INTEGER NOT NULL DEFAULT 0, highlights_json TEXT NOT NULL DEFAULT '[]', speakers_json TEXT NOT NULL DEFAULT '[]', agenda_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS registrations (id TEXT PRIMARY KEY, application_no TEXT NOT NULL UNIQUE, event_id TEXT NOT NULL REFERENCES events(id), name_zh TEXT NOT NULL, name_en TEXT NOT NULL DEFAULT '', organization TEXT NOT NULL, department TEXT NOT NULL DEFAULT '', job_title TEXT NOT NULL, category TEXT NOT NULL, mobile TEXT NOT NULL, email TEXT NOT NULL, email_normalized TEXT NOT NULL, needs_english_badge INTEGER NOT NULL DEFAULT 0, dietary TEXT NOT NULL DEFAULT '', dietary_notes TEXT NOT NULL DEFAULT '', accessibility_needs TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', accepts_updates INTEGER NOT NULL DEFAULT 0, privacy_consent INTEGER NOT NULL, status TEXT NOT NULL, checkin_token TEXT UNIQUE, checked_in_at TEXT, custom_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(event_id, email_normalized));
CREATE TABLE IF NOT EXISTS registration_history (id TEXT PRIMARY KEY, registration_id TEXT NOT NULL REFERENCES registrations(id), from_status TEXT, to_status TEXT NOT NULL, actor_id TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS email_logs (id TEXT PRIMARY KEY, registration_id TEXT, template_key TEXT NOT NULL, recipient TEXT NOT NULL, status TEXT NOT NULL, error_message TEXT, actor_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, window_started_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_registrations_event_email ON registrations(event_id,email_normalized);
CREATE INDEX IF NOT EXISTS idx_registrations_event_status ON registrations(event_id,status);
CREATE INDEX IF NOT EXISTS idx_registrations_created_at ON registrations(created_at);
CREATE INDEX IF NOT EXISTS idx_history_registration ON registration_history(registration_id,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_logs(created_at);
PRAGMA optimize;
