"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";

type Result={registration:{nameZh:string;organization:string;applicationNo:string;checkedInAt:string|null};duplicate:boolean};
export default function CheckInPage(){const [query,setQuery]=useState("");const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState("");const [scanning,setScanning]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);
  useEffect(()=>{const token=new URLSearchParams(location.search).get("token");if(token)void submit({token});return()=>streamRef.current?.getTracks().forEach((t)=>t.stop());},[]);
  async function submit(payload:{token?:string;search?:string}){setError("");setResult(null);const res=await fetch("/api/admin/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as Result&{error?:string};if(res.ok)setResult(data);else setError(data.error||"無法完成報到");}
  async function startScanner(){setError("");if(!navigator.mediaDevices?.getUserMedia){setError("此裝置無法啟用相機，請改用搜尋報到。");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}setScanning(true);const Detector=(window as unknown as {BarcodeDetector?:new(o:{formats:string[]})=>{detect(v:HTMLVideoElement):Promise<{rawValue:string}[]>}}).BarcodeDetector;if(!Detector){setError("此瀏覽器不支援內建 QR 掃描，請輸入申請編號或使用 QR 連結。");return;}const detector=new Detector({formats:["qr_code"]});const loop=async()=>{if(!streamRef.current||!videoRef.current)return;const codes=await detector.detect(videoRef.current).catch(()=>[]);if(codes[0]){const raw=codes[0].rawValue;const token=new URL(raw,location.origin).searchParams.get("token")||raw;stopScanner();await submit({token});return;}requestAnimationFrame(loop);};void loop();}catch{setError("無法使用相機，請確認權限或改用搜尋報到。");}}
  function stopScanner(){streamRef.current?.getTracks().forEach((t)=>t.stop());streamRef.current=null;setScanning(false);}
  return <main className="checkin-page"><header><Link href="/admin">← 返回管理後台</Link><span>2026 IRMF · 現場報到</span><b>即時連線</b></header><section><div className="checkin-intro"><span className="eyebrow light">ON-SITE CHECK-IN</span><h1>現場報到</h1><p>掃描與會者專屬 QR Code，或以姓名、手機末三碼、申請編號查詢。</p></div><div className="checkin-grid"><div className="scanner"><video ref={videoRef} playsInline muted/><div className="scan-frame"><i/><i/><i/><i/></div>{!scanning?<button onClick={startScanner}>啟用相機掃描</button>:<button onClick={stopScanner}>停止掃描</button>}<p>相機資料只用於裝置端辨識，不會儲存影像。</p></div><div className="manual-checkin"><span>無法掃碼？</span><h2>搜尋報到</h2><form onSubmit={(e)=>{e.preventDefault();void submit({search:query})}}><label htmlFor="checkin-search">姓名、手機末三碼或申請編號</label><input id="checkin-search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="例如：IRMF-2026-XXXXXXXX"/><button>查詢並報到 →</button></form>{error&&<div className="checkin-error" role="alert"><b>無法完成報到</b><p>{error}</p><button onClick={()=>setError("")}>重新嘗試</button></div>}{result&&<div className={result.duplicate?"checkin-result duplicate":"checkin-result"}><span>{result.duplicate?"!":"✓"}</span><h2>{result.duplicate?"重複報到提醒":"報到成功"}</h2><strong>{result.registration.nameZh}</strong><p>{result.registration.organization}</p><small>{result.registration.applicationNo}</small>{result.registration.checkedInAt&&<time>{new Date(result.registration.checkedInAt).toLocaleString("zh-TW")}</time>}</div>}</div></div></section></main>;
}
